<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ProcDomainSniffer.GUI</AssemblyName>
    <RootNamespace>ProcDomainSniffer.GUI</RootNamespace>

    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <ApplicationIcon>Assets\ProcDomainSniffer.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProcDomainSniffer.Core\ProcDomainSniffer.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\ProcDomainSnifferIcon.png" />
  </ItemGroup>
</Project>
